image: danhdue/flutter:3.3.9

stages:
  - CIChecking

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - chmod +x ./gradlew
  - echo $ANDROID_HOME
  - mkdir .ci-reports

CIChecking:
  dependencies: []
  stage: CIChecking
  cache:
    paths:
      - ./.gradle
      - ./build
      - ./app/build
      - ./build-caches
  artifacts:
    paths:
      - .ci-reports
  script:
    - melos testWithCoverage
    - melos buildAPKRelease
    - melos androidBetaDistribute
  tags:
    - gitlab-server-docker
