name: getx_sample
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  fimber: ^0.6.6
  flutter_hooks: ^0.18.5+1
  visibility_detector: ^0.3.3
  flutter_keyboard_visibility: ^5.3.0
  lottie: ^1.4.3
  flutter_svg: 2.0.3
  shimmer: ^2.0.0
  intl: ^0.17.0
  jiffy: ^5.0.0
  rxdart: ^0.27.5
  path_provider: ^2.0.11
  path_provider_android: ^2.0.20
  path_provider_ios: ^2.0.11
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^4.0.6
  json_annotation: ^4.7.0
  freezed_annotation: ^2.1.0
  auto_size_text: ^3.0.0
  connectivity_plus: ^2.3.7
  flutter_local_notifications: ^11.0.1
  flutter_native_timezone: ^2.0.0
  equatable: ^2.0.5
  theme_tailor_annotation: ^1.0.3
  cached_network_image: ^3.2.2
  carousel_slider: ^4.1.1
  get: 4.6.5
  dotted_line: ^3.1.0
  local_auth: ^2.1.2
  cryptography_flutter: ^2.3.0
  video_player: ^2.4.7
  flutter_easyloading: ^3.0.5
  dart_extensions: 2.2.0
  google_maps_flutter: ^2.2.5
  flutter_polyline_points: 1.0.0
  location: 4.4.0
  custom_info_window: 1.0.1
  clippy_flutter: 2.0.0-nullsafety.1
  melos: 3.0.1
  flutter_quill: 7.1.13
  appflowy_editor: 0.1.10
  flutter: 
    sdk: flutter
  animated_bottom_navigation_bar: 
    git: 
      url: https://github.com/DanhDue/animated-bottom-navigation-bar-flutter.git
      ref: disable-active-scale-animation
  sliding_up_panel2: 
    git: 
      url: https://github.com/D3FOutsourcing/sliding_up_panel.git
      ref: scrolling-in-the-minimized-state
  annotations: 
    path: lib/utils/annotations/
  quill_html_editor: 2.1.8
  pdf: 3.10.1
  printing: ^5.10.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  test: ^1.21.4
  build_runner: ^2.2.1
  http_mock_adapter: ^0.3.3
  json_serializable: ^6.4.1
  hive_generator: ^1.1.3
  freezed: ^2.1.0+1
  flutter_gen_runner: 5.2.0
  theme_tailor: ^1.0.6
  mockito: ^5.3.2
  hive_test: ^1.0.1
  retrofit_generator: ^4.2.0
  flutter_native_splash: ^2.2.16
  flutter_test: 
    sdk: flutter
  generators: 
    path: lib/utils/generators/
  # get_cli: ^1.8.1

dartfmt: 
  line_length: 99

flutter_gen: 
  output: lib/generated/
  integrations: 
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: true
    json: true
  assets: 
    outputs: 
      class_name: Assets
      style: dot-delimiter
      package_parameter_enabled: false
    enabled: true
  colors: 
    outputs: 
      class_name: LMSColors
      style: dot-delimiter
      package_parameter_enabled: false
    inputs: 
      - assets/colors/colors.xml
    enable: true
  fonts: 
    outputs: 
      class_name: LMSFontFamily
    enabled: true
  line_length: 99

flutter: 
  assets: 
    - assets/images/
    - assets/lotties/
    - assets/jsons/
    - web/assets/images/
  fonts: 
    - family: SfCompactRegular
      fonts: 
        - asset: assets/fonts/SF_Compact_Display_Regular.ttf
    - family: SfCompactMedium
      fonts: 
        - asset: assets/fonts/SF_Compact_Display_Medium.ttf
    - family: SfCompactSemiBold
      fonts: 
        - asset: assets/fonts/SF_Compact_Display_Semibold.ttf
    - family: SfCompactBold
      fonts: 
        - asset: assets/fonts/SF_Compact_Display_Bold.ttf
  uses-material-design: true
