#!/bin/bash
# This bash script is used for saving all remotes from the git used on a project to .gitremotes file.
# command: git remote-save
gitTop=$( git rev-parse --show-toplevel 2> /dev/null )
[[ "" == "$gitTop" ]] && exit 0
gitRemotes=$gitTop/.gitremotes
[[ "$( git remote -v )" == "" ]] && exit 0
git remote -v > $gitRemotes
