#!/bin/bash
# This bash script is used for adding a remote from .gitremotes file to the git used on a project.
# command: git remote-init
gitTop=$( git rev-parse --show-toplevel 2> /dev/null )
[[ "" == "$gitTop" ]] && exit 0
gitRemotes=$gitTop/.gitremotes
[[ ! -e $gitRemotes ]] && exit 0
# if exists added remote repos then exit
[[ "$( git remote -v )" == "" ]] && exit 0
remotes=$(sed '/origin/d' $gitRemotes | awk 'NR%2==0 {print $1";"$2 }')
for r in $remotes ; do
	git remote add $(echo $r | sed 's/;/ /')
done
